/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Assessment generated by hbm2java
 */
@Entity
@Table(name="`assessment`"
    ,schema="data"
)

public class Assessment  implements java.io.Serializable {

    
    private Integer id;
    
    private Date updatedTimestamp;
    
    private Integer taxYear;
    
    private String assesseeName;
    
    private String assesseeAddressLine1;
    
    private String assesseeAddressCity;
    
    private String assesseeAddressState;
    
    private String assesseeAddressZip;
    
    private Double assessedValuationLand;
    
    private Double equalizedValuation;
    
    private Double assessedValuationBuilding;
    
    private Double assessedValuationTotal;
    
    private Double homeExemption;
    
    private Double seniorExemption;
    
    private Boolean seniorFreeze;
    
    private Double marketValue;
    
    private String conditionRating;
    
    private String qualityRating;
    
    private Integer lastImportId;
    
    private Property property;
    
    private PropertyClass propertyClass;

    public Assessment() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`ID`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`updated_timestamp`", length=10)
    public Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    

    @Column(name="`tax_year`", precision=10)
    public Integer getTaxYear() {
        return this.taxYear;
    }
    
    public void setTaxYear(Integer taxYear) {
        this.taxYear = taxYear;
    }

    

    @Column(name="`assessee_name`", length=100)
    public String getAssesseeName() {
        return this.assesseeName;
    }
    
    public void setAssesseeName(String assesseeName) {
        this.assesseeName = assesseeName;
    }

    

    @Column(name="`assessee_address_line1`", length=100)
    public String getAssesseeAddressLine1() {
        return this.assesseeAddressLine1;
    }
    
    public void setAssesseeAddressLine1(String assesseeAddressLine1) {
        this.assesseeAddressLine1 = assesseeAddressLine1;
    }

    

    @Column(name="`assessee_address_city`", length=50)
    public String getAssesseeAddressCity() {
        return this.assesseeAddressCity;
    }
    
    public void setAssesseeAddressCity(String assesseeAddressCity) {
        this.assesseeAddressCity = assesseeAddressCity;
    }

    

    @Column(name="`assessee_address_state`", length=2)
    public String getAssesseeAddressState() {
        return this.assesseeAddressState;
    }
    
    public void setAssesseeAddressState(String assesseeAddressState) {
        this.assesseeAddressState = assesseeAddressState;
    }

    

    @Column(name="`assessee_address_zip`", length=10)
    public String getAssesseeAddressZip() {
        return this.assesseeAddressZip;
    }
    
    public void setAssesseeAddressZip(String assesseeAddressZip) {
        this.assesseeAddressZip = assesseeAddressZip;
    }

    

    @Column(name="`assessed_valuation_land`", scale=4)
    public Double getAssessedValuationLand() {
        return this.assessedValuationLand;
    }
    
    public void setAssessedValuationLand(Double assessedValuationLand) {
        this.assessedValuationLand = assessedValuationLand;
    }

    

    @Column(name="`equalized_valuation`", scale=4)
    public Double getEqualizedValuation() {
        return this.equalizedValuation;
    }
    
    public void setEqualizedValuation(Double equalizedValuation) {
        this.equalizedValuation = equalizedValuation;
    }

    

    @Column(name="`assessed_valuation_building`", scale=4)
    public Double getAssessedValuationBuilding() {
        return this.assessedValuationBuilding;
    }
    
    public void setAssessedValuationBuilding(Double assessedValuationBuilding) {
        this.assessedValuationBuilding = assessedValuationBuilding;
    }

    

    @Column(name="`assessed_valuation_total`", scale=4)
    public Double getAssessedValuationTotal() {
        return this.assessedValuationTotal;
    }
    
    public void setAssessedValuationTotal(Double assessedValuationTotal) {
        this.assessedValuationTotal = assessedValuationTotal;
    }

    

    @Column(name="`home_exemption`", scale=4)
    public Double getHomeExemption() {
        return this.homeExemption;
    }
    
    public void setHomeExemption(Double homeExemption) {
        this.homeExemption = homeExemption;
    }

    

    @Column(name="`senior_exemption`", scale=4)
    public Double getSeniorExemption() {
        return this.seniorExemption;
    }
    
    public void setSeniorExemption(Double seniorExemption) {
        this.seniorExemption = seniorExemption;
    }

    

    @Column(name="`senior_freeze`")
    public Boolean getSeniorFreeze() {
        return this.seniorFreeze;
    }
    
    public void setSeniorFreeze(Boolean seniorFreeze) {
        this.seniorFreeze = seniorFreeze;
    }

    

    @Column(name="`market_value`", scale=4)
    public Double getMarketValue() {
        return this.marketValue;
    }
    
    public void setMarketValue(Double marketValue) {
        this.marketValue = marketValue;
    }

    

    @Column(name="`condition_rating`", length=50)
    public String getConditionRating() {
        return this.conditionRating;
    }
    
    public void setConditionRating(String conditionRating) {
        this.conditionRating = conditionRating;
    }

    

    @Column(name="`quality_rating`", length=50)
    public String getQualityRating() {
        return this.qualityRating;
    }
    
    public void setQualityRating(String qualityRating) {
        this.qualityRating = qualityRating;
    }

    

    @Column(name="`last_import_id`", precision=10)
    public Integer getLastImportId() {
        return this.lastImportId;
    }
    
    public void setLastImportId(Integer lastImportId) {
        this.lastImportId = lastImportId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`property_id`")
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`property_class_id`")
    public PropertyClass getPropertyClass() {
        return this.propertyClass;
    }
    
    public void setPropertyClass(PropertyClass propertyClass) {
        this.propertyClass = propertyClass;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Assessment) )
		    return false;

		 Assessment that = (Assessment) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

