/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.math.BigDecimal;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * AuctionStatId generated by hbm2java
 */
@Embeddable
public class AuctionStatId  implements java.io.Serializable {

    
    private Integer auctionId;
    
    private Integer auctionYear;
    
    private BigDecimal lifetimeInvestment;
    
    private Integer countPublished;
    
    private Integer countAuctioned;
    
    private Integer countForfeited;
    
    private Integer countOpensales;
    
    private Integer countOpenpriors;

    public AuctionStatId() {
    }


    public Integer getAuctionId() {
        return this.auctionId;
    }
    
    public void setAuctionId(Integer auctionId) {
        this.auctionId = auctionId;
    }
    public Integer getAuctionYear() {
        return this.auctionYear;
    }
    
    public void setAuctionYear(Integer auctionYear) {
        this.auctionYear = auctionYear;
    }
    public BigDecimal getLifetimeInvestment() {
        return this.lifetimeInvestment;
    }
    
    public void setLifetimeInvestment(BigDecimal lifetimeInvestment) {
        this.lifetimeInvestment = lifetimeInvestment;
    }
    public Integer getCountPublished() {
        return this.countPublished;
    }
    
    public void setCountPublished(Integer countPublished) {
        this.countPublished = countPublished;
    }
    public Integer getCountAuctioned() {
        return this.countAuctioned;
    }
    
    public void setCountAuctioned(Integer countAuctioned) {
        this.countAuctioned = countAuctioned;
    }
    public Integer getCountForfeited() {
        return this.countForfeited;
    }
    
    public void setCountForfeited(Integer countForfeited) {
        this.countForfeited = countForfeited;
    }
    public Integer getCountOpensales() {
        return this.countOpensales;
    }
    
    public void setCountOpensales(Integer countOpensales) {
        this.countOpensales = countOpensales;
    }
    public Integer getCountOpenpriors() {
        return this.countOpenpriors;
    }
    
    public void setCountOpenpriors(Integer countOpenpriors) {
        this.countOpenpriors = countOpenpriors;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof AuctionStatId) )
		    return false;

		 AuctionStatId that = (AuctionStatId) o;

         return ( (this.getAuctionId()==that.getAuctionId()) || ( this.getAuctionId()!=null && that.getAuctionId()!=null && this.getAuctionId().equals(that.getAuctionId()) ) )
 && ( (this.getAuctionYear()==that.getAuctionYear()) || ( this.getAuctionYear()!=null && that.getAuctionYear()!=null && this.getAuctionYear().equals(that.getAuctionYear()) ) )
 && ( (this.getLifetimeInvestment()==that.getLifetimeInvestment()) || ( this.getLifetimeInvestment()!=null && that.getLifetimeInvestment()!=null && this.getLifetimeInvestment().equals(that.getLifetimeInvestment()) ) )
 && ( (this.getCountPublished()==that.getCountPublished()) || ( this.getCountPublished()!=null && that.getCountPublished()!=null && this.getCountPublished().equals(that.getCountPublished()) ) )
 && ( (this.getCountAuctioned()==that.getCountAuctioned()) || ( this.getCountAuctioned()!=null && that.getCountAuctioned()!=null && this.getCountAuctioned().equals(that.getCountAuctioned()) ) )
 && ( (this.getCountForfeited()==that.getCountForfeited()) || ( this.getCountForfeited()!=null && that.getCountForfeited()!=null && this.getCountForfeited().equals(that.getCountForfeited()) ) )
 && ( (this.getCountOpensales()==that.getCountOpensales()) || ( this.getCountOpensales()!=null && that.getCountOpensales()!=null && this.getCountOpensales().equals(that.getCountOpensales()) ) )
 && ( (this.getCountOpenpriors()==that.getCountOpenpriors()) || ( this.getCountOpenpriors()!=null && that.getCountOpenpriors()!=null && this.getCountOpenpriors().equals(that.getCountOpenpriors()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAuctionId() == null ? 0 : this.getAuctionId().hashCode() );
         result = 37 * result + ( getAuctionYear() == null ? 0 : this.getAuctionYear().hashCode() );
         result = 37 * result + ( getLifetimeInvestment() == null ? 0 : this.getLifetimeInvestment().hashCode() );
         result = 37 * result + ( getCountPublished() == null ? 0 : this.getCountPublished().hashCode() );
         result = 37 * result + ( getCountAuctioned() == null ? 0 : this.getCountAuctioned().hashCode() );
         result = 37 * result + ( getCountForfeited() == null ? 0 : this.getCountForfeited().hashCode() );
         result = 37 * result + ( getCountOpensales() == null ? 0 : this.getCountOpensales().hashCode() );
         result = 37 * result + ( getCountOpenpriors() == null ? 0 : this.getCountOpenpriors().hashCode() );

         return result;
    }


}

