/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * BorrowingBase generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`borrowing_base`", schema = "servicing")
@IdClass(BorrowingBaseId.class)
public class BorrowingBase implements Serializable {

    private String state;
    private String county;
    private int taxYear;
    private Double certificatePrincipal;
    private Double subPrincipal;
    private Double trustReceipt;

    @Id
    @Column(name = "`State`", nullable = false, length = 2)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Id
    @Column(name = "`County`", nullable = true, length = 51)
    public String getCounty() {
        return this.county;
    }

    public void setCounty(String county) {
        this.county = county;
    }

    @Id
    @Column(name = "`Tax Year`", nullable = false, scale = 0, precision = 10)
    public int getTaxYear() {
        return this.taxYear;
    }

    public void setTaxYear(int taxYear) {
        this.taxYear = taxYear;
    }

    @Id
    @Column(name = "`Certificate Principal`", nullable = true, scale = 4, precision = 19)
    public Double getCertificatePrincipal() {
        return this.certificatePrincipal;
    }

    public void setCertificatePrincipal(Double certificatePrincipal) {
        this.certificatePrincipal = certificatePrincipal;
    }

    @Id
    @Column(name = "`Sub Principal`", nullable = true, scale = 4, precision = 19)
    public Double getSubPrincipal() {
        return this.subPrincipal;
    }

    public void setSubPrincipal(Double subPrincipal) {
        this.subPrincipal = subPrincipal;
    }

    @Id
    @Column(name = "`Trust Receipt`", nullable = true, scale = 4, precision = 19)
    public Double getTrustReceipt() {
        return this.trustReceipt;
    }

    public void setTrustReceipt(Double trustReceipt) {
        this.trustReceipt = trustReceipt;
    }



    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BorrowingBase)) return false;
        final BorrowingBase borrowingBase = (BorrowingBase) o;
        return Objects.equals(getState(), borrowingBase.getState()) &&
                Objects.equals(getCounty(), borrowingBase.getCounty()) &&
                Objects.equals(getTaxYear(), borrowingBase.getTaxYear()) &&
                Objects.equals(getCertificatePrincipal(), borrowingBase.getCertificatePrincipal()) &&
                Objects.equals(getSubPrincipal(), borrowingBase.getSubPrincipal()) &&
                Objects.equals(getTrustReceipt(), borrowingBase.getTrustReceipt());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getState(),
                getCounty(),
                getTaxYear(),
                getCertificatePrincipal(),
                getSubPrincipal(),
                getTrustReceipt());
    }
}

