/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.math.BigDecimal;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ModelPostingAvailabilityId generated by hbm2java
 */
@Embeddable
public class ModelPostingAvailabilityId  implements java.io.Serializable {

    
    private Integer auctionId;
    
    private BigDecimal sub1Pct;
    
    private BigDecimal sub2Pct;
    
    private BigDecimal sub3Pct;
    
    private BigDecimal sub4Pct;
    
    private BigDecimal sub5Pct;
    
    private BigDecimal sub6Pct;

    public ModelPostingAvailabilityId() {
    }


    public Integer getAuctionId() {
        return this.auctionId;
    }
    
    public void setAuctionId(Integer auctionId) {
        this.auctionId = auctionId;
    }
    public BigDecimal getSub1Pct() {
        return this.sub1Pct;
    }
    
    public void setSub1Pct(BigDecimal sub1Pct) {
        this.sub1Pct = sub1Pct;
    }
    public BigDecimal getSub2Pct() {
        return this.sub2Pct;
    }
    
    public void setSub2Pct(BigDecimal sub2Pct) {
        this.sub2Pct = sub2Pct;
    }
    public BigDecimal getSub3Pct() {
        return this.sub3Pct;
    }
    
    public void setSub3Pct(BigDecimal sub3Pct) {
        this.sub3Pct = sub3Pct;
    }
    public BigDecimal getSub4Pct() {
        return this.sub4Pct;
    }
    
    public void setSub4Pct(BigDecimal sub4Pct) {
        this.sub4Pct = sub4Pct;
    }
    public BigDecimal getSub5Pct() {
        return this.sub5Pct;
    }
    
    public void setSub5Pct(BigDecimal sub5Pct) {
        this.sub5Pct = sub5Pct;
    }
    public BigDecimal getSub6Pct() {
        return this.sub6Pct;
    }
    
    public void setSub6Pct(BigDecimal sub6Pct) {
        this.sub6Pct = sub6Pct;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ModelPostingAvailabilityId) )
		    return false;

		 ModelPostingAvailabilityId that = (ModelPostingAvailabilityId) o;

         return ( (this.getAuctionId()==that.getAuctionId()) || ( this.getAuctionId()!=null && that.getAuctionId()!=null && this.getAuctionId().equals(that.getAuctionId()) ) )
 && ( (this.getSub1Pct()==that.getSub1Pct()) || ( this.getSub1Pct()!=null && that.getSub1Pct()!=null && this.getSub1Pct().equals(that.getSub1Pct()) ) )
 && ( (this.getSub2Pct()==that.getSub2Pct()) || ( this.getSub2Pct()!=null && that.getSub2Pct()!=null && this.getSub2Pct().equals(that.getSub2Pct()) ) )
 && ( (this.getSub3Pct()==that.getSub3Pct()) || ( this.getSub3Pct()!=null && that.getSub3Pct()!=null && this.getSub3Pct().equals(that.getSub3Pct()) ) )
 && ( (this.getSub4Pct()==that.getSub4Pct()) || ( this.getSub4Pct()!=null && that.getSub4Pct()!=null && this.getSub4Pct().equals(that.getSub4Pct()) ) )
 && ( (this.getSub5Pct()==that.getSub5Pct()) || ( this.getSub5Pct()!=null && that.getSub5Pct()!=null && this.getSub5Pct().equals(that.getSub5Pct()) ) )
 && ( (this.getSub6Pct()==that.getSub6Pct()) || ( this.getSub6Pct()!=null && that.getSub6Pct()!=null && this.getSub6Pct().equals(that.getSub6Pct()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAuctionId() == null ? 0 : this.getAuctionId().hashCode() );
         result = 37 * result + ( getSub1Pct() == null ? 0 : this.getSub1Pct().hashCode() );
         result = 37 * result + ( getSub2Pct() == null ? 0 : this.getSub2Pct().hashCode() );
         result = 37 * result + ( getSub3Pct() == null ? 0 : this.getSub3Pct().hashCode() );
         result = 37 * result + ( getSub4Pct() == null ? 0 : this.getSub4Pct().hashCode() );
         result = 37 * result + ( getSub5Pct() == null ? 0 : this.getSub5Pct().hashCode() );
         result = 37 * result + ( getSub6Pct() == null ? 0 : this.getSub6Pct().hashCode() );

         return result;
    }


}

