/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ModelHistoricalAuctionsId generated by hbm2java
 */
@Embeddable
public class ModelHistoricalAuctionsId  implements java.io.Serializable {

    
    private Integer auctionId;
    
    private Integer auctionYear;
    
    private Integer countPublished;
    
    private Integer countAuctioned;
    
    private Integer countForfeited;
    
    private Integer countOpensales;
    
    private Integer countOpenpriors;
    
    private Integer taxYear1;
    
    private String auctionResult1;
    
    private String dispositionStatus1;
    
    private java.util.Date dispositionDate1;
    
    private String openStatus1;
    
    private Integer taxYear2;
    
    private String auctionResult2;
    
    private String dispositionStatus2;
    
    private java.util.Date dispositionDate2;
    
    private String openStatus2;
    
    private Integer taxYear3;
    
    private String auctionResult3;
    
    private String dispositionStatus3;
    
    private java.util.Date dispositionDate3;
    
    private String openStatus3;
    
    private Integer taxYear4;
    
    private String auctionResult4;
    
    private String dispositionStatus4;
    
    private java.util.Date dispositionDate4;
    
    private String openStatus4;
    
    private Integer taxYear5;
    
    private String auctionResult5;
    
    private String dispositionStatus5;
    
    private java.util.Date dispositionDate5;
    
    private String openStatus5;

    public ModelHistoricalAuctionsId() {
    }


    public Integer getAuctionId() {
        return this.auctionId;
    }
    
    public void setAuctionId(Integer auctionId) {
        this.auctionId = auctionId;
    }
    public Integer getAuctionYear() {
        return this.auctionYear;
    }
    
    public void setAuctionYear(Integer auctionYear) {
        this.auctionYear = auctionYear;
    }
    public Integer getCountPublished() {
        return this.countPublished;
    }
    
    public void setCountPublished(Integer countPublished) {
        this.countPublished = countPublished;
    }
    public Integer getCountAuctioned() {
        return this.countAuctioned;
    }
    
    public void setCountAuctioned(Integer countAuctioned) {
        this.countAuctioned = countAuctioned;
    }
    public Integer getCountForfeited() {
        return this.countForfeited;
    }
    
    public void setCountForfeited(Integer countForfeited) {
        this.countForfeited = countForfeited;
    }
    public Integer getCountOpensales() {
        return this.countOpensales;
    }
    
    public void setCountOpensales(Integer countOpensales) {
        this.countOpensales = countOpensales;
    }
    public Integer getCountOpenpriors() {
        return this.countOpenpriors;
    }
    
    public void setCountOpenpriors(Integer countOpenpriors) {
        this.countOpenpriors = countOpenpriors;
    }
    public Integer getTaxYear1() {
        return this.taxYear1;
    }
    
    public void setTaxYear1(Integer taxYear1) {
        this.taxYear1 = taxYear1;
    }
    public String getAuctionResult1() {
        return this.auctionResult1;
    }
    
    public void setAuctionResult1(String auctionResult1) {
        this.auctionResult1 = auctionResult1;
    }
    public String getDispositionStatus1() {
        return this.dispositionStatus1;
    }
    
    public void setDispositionStatus1(String dispositionStatus1) {
        this.dispositionStatus1 = dispositionStatus1;
    }
    public java.util.Date getDispositionDate1() {
        return this.dispositionDate1;
    }
    
    public void setDispositionDate1(java.util.Date dispositionDate1) {
        this.dispositionDate1 = dispositionDate1;
    }
    public String getOpenStatus1() {
        return this.openStatus1;
    }
    
    public void setOpenStatus1(String openStatus1) {
        this.openStatus1 = openStatus1;
    }
    public Integer getTaxYear2() {
        return this.taxYear2;
    }
    
    public void setTaxYear2(Integer taxYear2) {
        this.taxYear2 = taxYear2;
    }
    public String getAuctionResult2() {
        return this.auctionResult2;
    }
    
    public void setAuctionResult2(String auctionResult2) {
        this.auctionResult2 = auctionResult2;
    }
    public String getDispositionStatus2() {
        return this.dispositionStatus2;
    }
    
    public void setDispositionStatus2(String dispositionStatus2) {
        this.dispositionStatus2 = dispositionStatus2;
    }
    public java.util.Date getDispositionDate2() {
        return this.dispositionDate2;
    }
    
    public void setDispositionDate2(java.util.Date dispositionDate2) {
        this.dispositionDate2 = dispositionDate2;
    }
    public String getOpenStatus2() {
        return this.openStatus2;
    }
    
    public void setOpenStatus2(String openStatus2) {
        this.openStatus2 = openStatus2;
    }
    public Integer getTaxYear3() {
        return this.taxYear3;
    }
    
    public void setTaxYear3(Integer taxYear3) {
        this.taxYear3 = taxYear3;
    }
    public String getAuctionResult3() {
        return this.auctionResult3;
    }
    
    public void setAuctionResult3(String auctionResult3) {
        this.auctionResult3 = auctionResult3;
    }
    public String getDispositionStatus3() {
        return this.dispositionStatus3;
    }
    
    public void setDispositionStatus3(String dispositionStatus3) {
        this.dispositionStatus3 = dispositionStatus3;
    }
    public java.util.Date getDispositionDate3() {
        return this.dispositionDate3;
    }
    
    public void setDispositionDate3(java.util.Date dispositionDate3) {
        this.dispositionDate3 = dispositionDate3;
    }
    public String getOpenStatus3() {
        return this.openStatus3;
    }
    
    public void setOpenStatus3(String openStatus3) {
        this.openStatus3 = openStatus3;
    }
    public Integer getTaxYear4() {
        return this.taxYear4;
    }
    
    public void setTaxYear4(Integer taxYear4) {
        this.taxYear4 = taxYear4;
    }
    public String getAuctionResult4() {
        return this.auctionResult4;
    }
    
    public void setAuctionResult4(String auctionResult4) {
        this.auctionResult4 = auctionResult4;
    }
    public String getDispositionStatus4() {
        return this.dispositionStatus4;
    }
    
    public void setDispositionStatus4(String dispositionStatus4) {
        this.dispositionStatus4 = dispositionStatus4;
    }
    public java.util.Date getDispositionDate4() {
        return this.dispositionDate4;
    }
    
    public void setDispositionDate4(java.util.Date dispositionDate4) {
        this.dispositionDate4 = dispositionDate4;
    }
    public String getOpenStatus4() {
        return this.openStatus4;
    }
    
    public void setOpenStatus4(String openStatus4) {
        this.openStatus4 = openStatus4;
    }
    public Integer getTaxYear5() {
        return this.taxYear5;
    }
    
    public void setTaxYear5(Integer taxYear5) {
        this.taxYear5 = taxYear5;
    }
    public String getAuctionResult5() {
        return this.auctionResult5;
    }
    
    public void setAuctionResult5(String auctionResult5) {
        this.auctionResult5 = auctionResult5;
    }
    public String getDispositionStatus5() {
        return this.dispositionStatus5;
    }
    
    public void setDispositionStatus5(String dispositionStatus5) {
        this.dispositionStatus5 = dispositionStatus5;
    }
    public java.util.Date getDispositionDate5() {
        return this.dispositionDate5;
    }
    
    public void setDispositionDate5(java.util.Date dispositionDate5) {
        this.dispositionDate5 = dispositionDate5;
    }
    public String getOpenStatus5() {
        return this.openStatus5;
    }
    
    public void setOpenStatus5(String openStatus5) {
        this.openStatus5 = openStatus5;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ModelHistoricalAuctionsId) )
		    return false;

		 ModelHistoricalAuctionsId that = (ModelHistoricalAuctionsId) o;

         return ( (this.getAuctionId()==that.getAuctionId()) || ( this.getAuctionId()!=null && that.getAuctionId()!=null && this.getAuctionId().equals(that.getAuctionId()) ) )
 && ( (this.getAuctionYear()==that.getAuctionYear()) || ( this.getAuctionYear()!=null && that.getAuctionYear()!=null && this.getAuctionYear().equals(that.getAuctionYear()) ) )
 && ( (this.getCountPublished()==that.getCountPublished()) || ( this.getCountPublished()!=null && that.getCountPublished()!=null && this.getCountPublished().equals(that.getCountPublished()) ) )
 && ( (this.getCountAuctioned()==that.getCountAuctioned()) || ( this.getCountAuctioned()!=null && that.getCountAuctioned()!=null && this.getCountAuctioned().equals(that.getCountAuctioned()) ) )
 && ( (this.getCountForfeited()==that.getCountForfeited()) || ( this.getCountForfeited()!=null && that.getCountForfeited()!=null && this.getCountForfeited().equals(that.getCountForfeited()) ) )
 && ( (this.getCountOpensales()==that.getCountOpensales()) || ( this.getCountOpensales()!=null && that.getCountOpensales()!=null && this.getCountOpensales().equals(that.getCountOpensales()) ) )
 && ( (this.getCountOpenpriors()==that.getCountOpenpriors()) || ( this.getCountOpenpriors()!=null && that.getCountOpenpriors()!=null && this.getCountOpenpriors().equals(that.getCountOpenpriors()) ) )
 && ( (this.getTaxYear1()==that.getTaxYear1()) || ( this.getTaxYear1()!=null && that.getTaxYear1()!=null && this.getTaxYear1().equals(that.getTaxYear1()) ) )
 && ( (this.getAuctionResult1()==that.getAuctionResult1()) || ( this.getAuctionResult1()!=null && that.getAuctionResult1()!=null && this.getAuctionResult1().equals(that.getAuctionResult1()) ) )
 && ( (this.getDispositionStatus1()==that.getDispositionStatus1()) || ( this.getDispositionStatus1()!=null && that.getDispositionStatus1()!=null && this.getDispositionStatus1().equals(that.getDispositionStatus1()) ) )
 && ( (this.getDispositionDate1()==that.getDispositionDate1()) || ( this.getDispositionDate1()!=null && that.getDispositionDate1()!=null && this.getDispositionDate1().equals(that.getDispositionDate1()) ) )
 && ( (this.getOpenStatus1()==that.getOpenStatus1()) || ( this.getOpenStatus1()!=null && that.getOpenStatus1()!=null && this.getOpenStatus1().equals(that.getOpenStatus1()) ) )
 && ( (this.getTaxYear2()==that.getTaxYear2()) || ( this.getTaxYear2()!=null && that.getTaxYear2()!=null && this.getTaxYear2().equals(that.getTaxYear2()) ) )
 && ( (this.getAuctionResult2()==that.getAuctionResult2()) || ( this.getAuctionResult2()!=null && that.getAuctionResult2()!=null && this.getAuctionResult2().equals(that.getAuctionResult2()) ) )
 && ( (this.getDispositionStatus2()==that.getDispositionStatus2()) || ( this.getDispositionStatus2()!=null && that.getDispositionStatus2()!=null && this.getDispositionStatus2().equals(that.getDispositionStatus2()) ) )
 && ( (this.getDispositionDate2()==that.getDispositionDate2()) || ( this.getDispositionDate2()!=null && that.getDispositionDate2()!=null && this.getDispositionDate2().equals(that.getDispositionDate2()) ) )
 && ( (this.getOpenStatus2()==that.getOpenStatus2()) || ( this.getOpenStatus2()!=null && that.getOpenStatus2()!=null && this.getOpenStatus2().equals(that.getOpenStatus2()) ) )
 && ( (this.getTaxYear3()==that.getTaxYear3()) || ( this.getTaxYear3()!=null && that.getTaxYear3()!=null && this.getTaxYear3().equals(that.getTaxYear3()) ) )
 && ( (this.getAuctionResult3()==that.getAuctionResult3()) || ( this.getAuctionResult3()!=null && that.getAuctionResult3()!=null && this.getAuctionResult3().equals(that.getAuctionResult3()) ) )
 && ( (this.getDispositionStatus3()==that.getDispositionStatus3()) || ( this.getDispositionStatus3()!=null && that.getDispositionStatus3()!=null && this.getDispositionStatus3().equals(that.getDispositionStatus3()) ) )
 && ( (this.getDispositionDate3()==that.getDispositionDate3()) || ( this.getDispositionDate3()!=null && that.getDispositionDate3()!=null && this.getDispositionDate3().equals(that.getDispositionDate3()) ) )
 && ( (this.getOpenStatus3()==that.getOpenStatus3()) || ( this.getOpenStatus3()!=null && that.getOpenStatus3()!=null && this.getOpenStatus3().equals(that.getOpenStatus3()) ) )
 && ( (this.getTaxYear4()==that.getTaxYear4()) || ( this.getTaxYear4()!=null && that.getTaxYear4()!=null && this.getTaxYear4().equals(that.getTaxYear4()) ) )
 && ( (this.getAuctionResult4()==that.getAuctionResult4()) || ( this.getAuctionResult4()!=null && that.getAuctionResult4()!=null && this.getAuctionResult4().equals(that.getAuctionResult4()) ) )
 && ( (this.getDispositionStatus4()==that.getDispositionStatus4()) || ( this.getDispositionStatus4()!=null && that.getDispositionStatus4()!=null && this.getDispositionStatus4().equals(that.getDispositionStatus4()) ) )
 && ( (this.getDispositionDate4()==that.getDispositionDate4()) || ( this.getDispositionDate4()!=null && that.getDispositionDate4()!=null && this.getDispositionDate4().equals(that.getDispositionDate4()) ) )
 && ( (this.getOpenStatus4()==that.getOpenStatus4()) || ( this.getOpenStatus4()!=null && that.getOpenStatus4()!=null && this.getOpenStatus4().equals(that.getOpenStatus4()) ) )
 && ( (this.getTaxYear5()==that.getTaxYear5()) || ( this.getTaxYear5()!=null && that.getTaxYear5()!=null && this.getTaxYear5().equals(that.getTaxYear5()) ) )
 && ( (this.getAuctionResult5()==that.getAuctionResult5()) || ( this.getAuctionResult5()!=null && that.getAuctionResult5()!=null && this.getAuctionResult5().equals(that.getAuctionResult5()) ) )
 && ( (this.getDispositionStatus5()==that.getDispositionStatus5()) || ( this.getDispositionStatus5()!=null && that.getDispositionStatus5()!=null && this.getDispositionStatus5().equals(that.getDispositionStatus5()) ) )
 && ( (this.getDispositionDate5()==that.getDispositionDate5()) || ( this.getDispositionDate5()!=null && that.getDispositionDate5()!=null && this.getDispositionDate5().equals(that.getDispositionDate5()) ) )
 && ( (this.getOpenStatus5()==that.getOpenStatus5()) || ( this.getOpenStatus5()!=null && that.getOpenStatus5()!=null && this.getOpenStatus5().equals(that.getOpenStatus5()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAuctionId() == null ? 0 : this.getAuctionId().hashCode() );
         result = 37 * result + ( getAuctionYear() == null ? 0 : this.getAuctionYear().hashCode() );
         result = 37 * result + ( getCountPublished() == null ? 0 : this.getCountPublished().hashCode() );
         result = 37 * result + ( getCountAuctioned() == null ? 0 : this.getCountAuctioned().hashCode() );
         result = 37 * result + ( getCountForfeited() == null ? 0 : this.getCountForfeited().hashCode() );
         result = 37 * result + ( getCountOpensales() == null ? 0 : this.getCountOpensales().hashCode() );
         result = 37 * result + ( getCountOpenpriors() == null ? 0 : this.getCountOpenpriors().hashCode() );
         result = 37 * result + ( getTaxYear1() == null ? 0 : this.getTaxYear1().hashCode() );
         result = 37 * result + ( getAuctionResult1() == null ? 0 : this.getAuctionResult1().hashCode() );
         result = 37 * result + ( getDispositionStatus1() == null ? 0 : this.getDispositionStatus1().hashCode() );
         result = 37 * result + ( getDispositionDate1() == null ? 0 : this.getDispositionDate1().hashCode() );
         result = 37 * result + ( getOpenStatus1() == null ? 0 : this.getOpenStatus1().hashCode() );
         result = 37 * result + ( getTaxYear2() == null ? 0 : this.getTaxYear2().hashCode() );
         result = 37 * result + ( getAuctionResult2() == null ? 0 : this.getAuctionResult2().hashCode() );
         result = 37 * result + ( getDispositionStatus2() == null ? 0 : this.getDispositionStatus2().hashCode() );
         result = 37 * result + ( getDispositionDate2() == null ? 0 : this.getDispositionDate2().hashCode() );
         result = 37 * result + ( getOpenStatus2() == null ? 0 : this.getOpenStatus2().hashCode() );
         result = 37 * result + ( getTaxYear3() == null ? 0 : this.getTaxYear3().hashCode() );
         result = 37 * result + ( getAuctionResult3() == null ? 0 : this.getAuctionResult3().hashCode() );
         result = 37 * result + ( getDispositionStatus3() == null ? 0 : this.getDispositionStatus3().hashCode() );
         result = 37 * result + ( getDispositionDate3() == null ? 0 : this.getDispositionDate3().hashCode() );
         result = 37 * result + ( getOpenStatus3() == null ? 0 : this.getOpenStatus3().hashCode() );
         result = 37 * result + ( getTaxYear4() == null ? 0 : this.getTaxYear4().hashCode() );
         result = 37 * result + ( getAuctionResult4() == null ? 0 : this.getAuctionResult4().hashCode() );
         result = 37 * result + ( getDispositionStatus4() == null ? 0 : this.getDispositionStatus4().hashCode() );
         result = 37 * result + ( getDispositionDate4() == null ? 0 : this.getDispositionDate4().hashCode() );
         result = 37 * result + ( getOpenStatus4() == null ? 0 : this.getOpenStatus4().hashCode() );
         result = 37 * result + ( getTaxYear5() == null ? 0 : this.getTaxYear5().hashCode() );
         result = 37 * result + ( getAuctionResult5() == null ? 0 : this.getAuctionResult5().hashCode() );
         result = 37 * result + ( getDispositionStatus5() == null ? 0 : this.getDispositionStatus5().hashCode() );
         result = 37 * result + ( getDispositionDate5() == null ? 0 : this.getDispositionDate5().hashCode() );
         result = 37 * result + ( getOpenStatus5() == null ? 0 : this.getOpenStatus5().hashCode() );

         return result;
    }


}

