/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Party generated by hbm2java
 */
@Entity
@Table(name="`party`"
    ,schema="servicing"
)

public class Party  implements java.io.Serializable {

    
    private Integer id;
    
    private java.util.Date createdTimestamp;
    
    private java.util.Date updatedTimestamp;
    
    private String class_;
    
    private Boolean piq;
    
    private String name;
    
    private String careOf;
    
    private String address;
    
    private String city;
    
    private String state;
    
    private String zip;
    
    private Integer abacusId;
    
    private Set<MatterParty> matterParties = new HashSet<MatterParty>(0);
    
    private Source sourceBySource2;
    
    private Source sourceBySource1;

    public Party() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`created_timestamp`", length=23)
    public java.util.Date getCreatedTimestamp() {
        return this.createdTimestamp;
    }
    
    public void setCreatedTimestamp(java.util.Date createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`updated_timestamp`", length=23)
    public java.util.Date getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }
    
    public void setUpdatedTimestamp(java.util.Date updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    

    @Column(name="`class`", length=50)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    

    @Column(name="`piq`")
    public Boolean getPiq() {
        return this.piq;
    }
    
    public void setPiq(Boolean piq) {
        this.piq = piq;
    }

    

    @Column(name="`name`", length=200)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    

    @Column(name="`care_of`", length=150)
    public String getCareOf() {
        return this.careOf;
    }
    
    public void setCareOf(String careOf) {
        this.careOf = careOf;
    }

    

    @Column(name="`address`", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    

    @Column(name="`city`", length=50)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    

    @Column(name="`state`", length=2)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    

    @Column(name="`zip`", length=10)
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    

    @Column(name="`abacus_id`", precision=10)
    public Integer getAbacusId() {
        return this.abacusId;
    }
    
    public void setAbacusId(Integer abacusId) {
        this.abacusId = abacusId;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="party")
    public Set<MatterParty> getMatterParties() {
        return this.matterParties;
    }
    
    public void setMatterParties(Set<MatterParty> matterParties) {
        this.matterParties = matterParties;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`source2`")
    public Source getSourceBySource2() {
        return this.sourceBySource2;
    }
    
    public void setSourceBySource2(Source sourceBySource2) {
        this.sourceBySource2 = sourceBySource2;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`source1`")
    public Source getSourceBySource1() {
        return this.sourceBySource1;
    }
    
    public void setSourceBySource1(Source sourceBySource1) {
        this.sourceBySource1 = sourceBySource1;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Party) )
		    return false;

		 Party that = (Party) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

