/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * PortalMatterFilterId generated by hbm2java
 */
@Embeddable
public class PortalMatterFilterId  implements java.io.Serializable {

    
    private Integer propertyId;
    
    private String countyName;
    
    private String certificateNumber;
    
    private Integer taxYear;
    
    private String status;
    
    private String pin;
    
    private Integer volume;
    
    private Date expirationDate;
    
    private String matterNumber;
    
    private Date closedDate;
    
    private Date filedDate;
    
    private Integer matterId;
    
    private Integer certificateId;

    public PortalMatterFilterId() {
    }


    public Integer getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }
    public String getCountyName() {
        return this.countyName;
    }
    
    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }
    public String getCertificateNumber() {
        return this.certificateNumber;
    }
    
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }
    public Integer getTaxYear() {
        return this.taxYear;
    }
    
    public void setTaxYear(Integer taxYear) {
        this.taxYear = taxYear;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }
    public Integer getVolume() {
        return this.volume;
    }
    
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
    public Date getExpirationDate() {
        return this.expirationDate;
    }
    
    public void setExpirationDate(Date expirationDate) {
        this.expirationDate = expirationDate;
    }
    public String getMatterNumber() {
        return this.matterNumber;
    }
    
    public void setMatterNumber(String matterNumber) {
        this.matterNumber = matterNumber;
    }
    public Date getClosedDate() {
        return this.closedDate;
    }
    
    public void setClosedDate(Date closedDate) {
        this.closedDate = closedDate;
    }
    public Date getFiledDate() {
        return this.filedDate;
    }
    
    public void setFiledDate(Date filedDate) {
        this.filedDate = filedDate;
    }
    public Integer getMatterId() {
        return this.matterId;
    }
    
    public void setMatterId(Integer matterId) {
        this.matterId = matterId;
    }
    public Integer getCertificateId() {
        return this.certificateId;
    }
    
    public void setCertificateId(Integer certificateId) {
        this.certificateId = certificateId;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof PortalMatterFilterId) )
		    return false;

		 PortalMatterFilterId that = (PortalMatterFilterId) o;

         return ( (this.getPropertyId()==that.getPropertyId()) || ( this.getPropertyId()!=null && that.getPropertyId()!=null && this.getPropertyId().equals(that.getPropertyId()) ) )
 && ( (this.getCountyName()==that.getCountyName()) || ( this.getCountyName()!=null && that.getCountyName()!=null && this.getCountyName().equals(that.getCountyName()) ) )
 && ( (this.getCertificateNumber()==that.getCertificateNumber()) || ( this.getCertificateNumber()!=null && that.getCertificateNumber()!=null && this.getCertificateNumber().equals(that.getCertificateNumber()) ) )
 && ( (this.getTaxYear()==that.getTaxYear()) || ( this.getTaxYear()!=null && that.getTaxYear()!=null && this.getTaxYear().equals(that.getTaxYear()) ) )
 && ( (this.getStatus()==that.getStatus()) || ( this.getStatus()!=null && that.getStatus()!=null && this.getStatus().equals(that.getStatus()) ) )
 && ( (this.getPin()==that.getPin()) || ( this.getPin()!=null && that.getPin()!=null && this.getPin().equals(that.getPin()) ) )
 && ( (this.getVolume()==that.getVolume()) || ( this.getVolume()!=null && that.getVolume()!=null && this.getVolume().equals(that.getVolume()) ) )
 && ( (this.getExpirationDate()==that.getExpirationDate()) || ( this.getExpirationDate()!=null && that.getExpirationDate()!=null && this.getExpirationDate().equals(that.getExpirationDate()) ) )
 && ( (this.getMatterNumber()==that.getMatterNumber()) || ( this.getMatterNumber()!=null && that.getMatterNumber()!=null && this.getMatterNumber().equals(that.getMatterNumber()) ) )
 && ( (this.getClosedDate()==that.getClosedDate()) || ( this.getClosedDate()!=null && that.getClosedDate()!=null && this.getClosedDate().equals(that.getClosedDate()) ) )
 && ( (this.getFiledDate()==that.getFiledDate()) || ( this.getFiledDate()!=null && that.getFiledDate()!=null && this.getFiledDate().equals(that.getFiledDate()) ) )
 && ( (this.getMatterId()==that.getMatterId()) || ( this.getMatterId()!=null && that.getMatterId()!=null && this.getMatterId().equals(that.getMatterId()) ) )
 && ( (this.getCertificateId()==that.getCertificateId()) || ( this.getCertificateId()!=null && that.getCertificateId()!=null && this.getCertificateId().equals(that.getCertificateId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getPropertyId() == null ? 0 : this.getPropertyId().hashCode() );
         result = 37 * result + ( getCountyName() == null ? 0 : this.getCountyName().hashCode() );
         result = 37 * result + ( getCertificateNumber() == null ? 0 : this.getCertificateNumber().hashCode() );
         result = 37 * result + ( getTaxYear() == null ? 0 : this.getTaxYear().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getPin() == null ? 0 : this.getPin().hashCode() );
         result = 37 * result + ( getVolume() == null ? 0 : this.getVolume().hashCode() );
         result = 37 * result + ( getExpirationDate() == null ? 0 : this.getExpirationDate().hashCode() );
         result = 37 * result + ( getMatterNumber() == null ? 0 : this.getMatterNumber().hashCode() );
         result = 37 * result + ( getClosedDate() == null ? 0 : this.getClosedDate().hashCode() );
         result = 37 * result + ( getFiledDate() == null ? 0 : this.getFiledDate().hashCode() );
         result = 37 * result + ( getMatterId() == null ? 0 : this.getMatterId().hashCode() );
         result = 37 * result + ( getCertificateId() == null ? 0 : this.getCertificateId().hashCode() );

         return result;
    }


}

