/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * PropertySale generated by hbm2java
 */
@Entity
@Table(name="`property_sale`"
    ,schema="data"
)

public class PropertySale  implements java.io.Serializable {

    
    private Integer id;
    
    private Date researchDate;
    
    private String researchSource;
    
    private Double deedCost;
    
    private Boolean priorAssignment;
    
    private Date saleDate;
    
    private Double saleAmount;
    
    private Integer lastImportId;
    
    private AuctionResult auctionResult;
    
    private Property property;
    
    private Research research;

    public PropertySale() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`research_date`", length=10)
    public Date getResearchDate() {
        return this.researchDate;
    }
    
    public void setResearchDate(Date researchDate) {
        this.researchDate = researchDate;
    }

    

    @Column(name="`research_source`", length=50)
    public String getResearchSource() {
        return this.researchSource;
    }
    
    public void setResearchSource(String researchSource) {
        this.researchSource = researchSource;
    }

    

    @Column(name="`deed_cost`", scale=4)
    public Double getDeedCost() {
        return this.deedCost;
    }
    
    public void setDeedCost(Double deedCost) {
        this.deedCost = deedCost;
    }

    

    @Column(name="`prior_assignment`")
    public Boolean getPriorAssignment() {
        return this.priorAssignment;
    }
    
    public void setPriorAssignment(Boolean priorAssignment) {
        this.priorAssignment = priorAssignment;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`sale_date`", length=10)
    public Date getSaleDate() {
        return this.saleDate;
    }
    
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    

    @Column(name="`sale_amount`", scale=4)
    public Double getSaleAmount() {
        return this.saleAmount;
    }
    
    public void setSaleAmount(Double saleAmount) {
        this.saleAmount = saleAmount;
    }

    

    @Column(name="`last_import_id`", precision=10)
    public Integer getLastImportId() {
        return this.lastImportId;
    }
    
    public void setLastImportId(Integer lastImportId) {
        this.lastImportId = lastImportId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`auction_result_id`")
    public AuctionResult getAuctionResult() {
        return this.auctionResult;
    }
    
    public void setAuctionResult(AuctionResult auctionResult) {
        this.auctionResult = auctionResult;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`property_id`")
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`research_bundle`")
    public Research getResearch() {
        return this.research;
    }
    
    public void setResearch(Research research) {
        this.research = research;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof PropertySale) )
		    return false;

		 PropertySale that = (PropertySale) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

