/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Research generated by hbm2java
 */
@Entity
@Table(name="`research`"
    ,schema="data"
)

public class Research  implements java.io.Serializable {

    
    private Integer id;
    
    private String type;
    
    private java.util.Date date;
    
    private Set<PropertySale> propertySales = new HashSet<PropertySale>(0);
    
    private Set<TaxHistory> taxHistories = new HashSet<TaxHistory>(0);
    
    private Set<TitleTransaction> titleTransactions = new HashSet<TitleTransaction>(0);
    
    private Property property;

    public Research() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`id`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`type`", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`date`", length=10)
    public java.util.Date getDate() {
        return this.date;
    }
    
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="research")
    public Set<PropertySale> getPropertySales() {
        return this.propertySales;
    }
    
    public void setPropertySales(Set<PropertySale> propertySales) {
        this.propertySales = propertySales;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="research")
    public Set<TaxHistory> getTaxHistories() {
        return this.taxHistories;
    }
    
    public void setTaxHistories(Set<TaxHistory> taxHistories) {
        this.taxHistories = taxHistories;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="research")
    public Set<TitleTransaction> getTitleTransactions() {
        return this.titleTransactions;
    }
    
    public void setTitleTransactions(Set<TitleTransaction> titleTransactions) {
        this.titleTransactions = titleTransactions;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`property_id`")
    public Property getProperty() {
        return this.property;
    }
    
    public void setProperty(Property property) {
        this.property = property;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Research) )
		    return false;

		 Research that = (Research) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

