/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rule generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`rule`", schema = "review")
public class Rule implements Serializable {

    private int id;
    private String name;
    private boolean active;
    private String includedCountyIds;
    private String newStatus;
    private BigDecimal modelScoreFloor;
    private BigDecimal modelScoreCeiling;
    private Integer openSalesFloor;
    private Integer openSalesCeiling;
    private Integer sieCountFloor;
    private Integer sieCountCeiling;
    private Double priorYearsDueFloor;
    private Double priorYearsDueCeiling;
    private Double saleAmountFloor;
    private Double saleAmountCeiling;
    private BigDecimal lifetimeLtvFloor;
    private BigDecimal lifetimeLtvCeiling;
    private Double marketValueFloor;
    private Double marketValueCeiling;
    private Character propertyClassFilter;
    private String propertyType;
    private String grades;
    private Boolean partialAssessment;
    private String tag;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "`name`", nullable = false, length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`active`", nullable = false)
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Column(name = "`included_county_ids`", nullable = false, length = 50)
    public String getIncludedCountyIds() {
        return this.includedCountyIds;
    }

    public void setIncludedCountyIds(String includedCountyIds) {
        this.includedCountyIds = includedCountyIds;
    }

    @Column(name = "`new_status`", nullable = false, length = 50)
    public String getNewStatus() {
        return this.newStatus;
    }

    public void setNewStatus(String newStatus) {
        this.newStatus = newStatus;
    }

    @Column(name = "`model_score_floor`", nullable = true, scale = 9, precision = 53)
    public BigDecimal getModelScoreFloor() {
        return this.modelScoreFloor;
    }

    public void setModelScoreFloor(BigDecimal modelScoreFloor) {
        this.modelScoreFloor = modelScoreFloor;
    }

    @Column(name = "`model_score_ceiling`", nullable = true, scale = 9, precision = 53)
    public BigDecimal getModelScoreCeiling() {
        return this.modelScoreCeiling;
    }

    public void setModelScoreCeiling(BigDecimal modelScoreCeiling) {
        this.modelScoreCeiling = modelScoreCeiling;
    }

    @Column(name = "`open_sales_floor`", nullable = true, scale = 0, precision = 10)
    public Integer getOpenSalesFloor() {
        return this.openSalesFloor;
    }

    public void setOpenSalesFloor(Integer openSalesFloor) {
        this.openSalesFloor = openSalesFloor;
    }

    @Column(name = "`open_sales_ceiling`", nullable = true, scale = 0, precision = 10)
    public Integer getOpenSalesCeiling() {
        return this.openSalesCeiling;
    }

    public void setOpenSalesCeiling(Integer openSalesCeiling) {
        this.openSalesCeiling = openSalesCeiling;
    }

    @Column(name = "`sie_count_floor`", nullable = true, scale = 0, precision = 10)
    public Integer getSieCountFloor() {
        return this.sieCountFloor;
    }

    public void setSieCountFloor(Integer sieCountFloor) {
        this.sieCountFloor = sieCountFloor;
    }

    @Column(name = "`sie_count_ceiling`", nullable = true, scale = 0, precision = 10)
    public Integer getSieCountCeiling() {
        return this.sieCountCeiling;
    }

    public void setSieCountCeiling(Integer sieCountCeiling) {
        this.sieCountCeiling = sieCountCeiling;
    }

    @Column(name = "`prior_years_due_floor`", nullable = true, scale = 4, precision = 19)
    public Double getPriorYearsDueFloor() {
        return this.priorYearsDueFloor;
    }

    public void setPriorYearsDueFloor(Double priorYearsDueFloor) {
        this.priorYearsDueFloor = priorYearsDueFloor;
    }

    @Column(name = "`prior_years_due_ceiling`", nullable = true, scale = 4, precision = 19)
    public Double getPriorYearsDueCeiling() {
        return this.priorYearsDueCeiling;
    }

    public void setPriorYearsDueCeiling(Double priorYearsDueCeiling) {
        this.priorYearsDueCeiling = priorYearsDueCeiling;
    }

    @Column(name = "`sale_amount_floor`", nullable = true, scale = 4, precision = 19)
    public Double getSaleAmountFloor() {
        return this.saleAmountFloor;
    }

    public void setSaleAmountFloor(Double saleAmountFloor) {
        this.saleAmountFloor = saleAmountFloor;
    }

    @Column(name = "`sale_amount_ceiling`", nullable = true, scale = 4, precision = 19)
    public Double getSaleAmountCeiling() {
        return this.saleAmountCeiling;
    }

    public void setSaleAmountCeiling(Double saleAmountCeiling) {
        this.saleAmountCeiling = saleAmountCeiling;
    }

    @Column(name = "`lifetime_ltv_floor`", nullable = true, scale = 9, precision = 53)
    public BigDecimal getLifetimeLtvFloor() {
        return this.lifetimeLtvFloor;
    }

    public void setLifetimeLtvFloor(BigDecimal lifetimeLtvFloor) {
        this.lifetimeLtvFloor = lifetimeLtvFloor;
    }

    @Column(name = "`lifetime_ltv_ceiling`", nullable = true, scale = 9, precision = 53)
    public BigDecimal getLifetimeLtvCeiling() {
        return this.lifetimeLtvCeiling;
    }

    public void setLifetimeLtvCeiling(BigDecimal lifetimeLtvCeiling) {
        this.lifetimeLtvCeiling = lifetimeLtvCeiling;
    }

    @Column(name = "`market_value_floor`", nullable = true, scale = 4, precision = 19)
    public Double getMarketValueFloor() {
        return this.marketValueFloor;
    }

    public void setMarketValueFloor(Double marketValueFloor) {
        this.marketValueFloor = marketValueFloor;
    }

    @Column(name = "`market_value_ceiling`", nullable = true, scale = 4, precision = 19)
    public Double getMarketValueCeiling() {
        return this.marketValueCeiling;
    }

    public void setMarketValueCeiling(Double marketValueCeiling) {
        this.marketValueCeiling = marketValueCeiling;
    }

    @Column(name = "`property_class_filter`", nullable = true, length = 1)
    public Character getPropertyClassFilter() {
        return this.propertyClassFilter;
    }

    public void setPropertyClassFilter(Character propertyClassFilter) {
        this.propertyClassFilter = propertyClassFilter;
    }

    @Column(name = "`property_type`", nullable = true, length = 50)
    public String getPropertyType() {
        return this.propertyType;
    }

    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }

    @Column(name = "`grades`", nullable = true, length = 50)
    public String getGrades() {
        return this.grades;
    }

    public void setGrades(String grades) {
        this.grades = grades;
    }

    @Column(name = "`partial_assessment`", nullable = true)
    public Boolean getPartialAssessment() {
        return this.partialAssessment;
    }

    public void setPartialAssessment(Boolean partialAssessment) {
        this.partialAssessment = partialAssessment;
    }

    @Column(name = "`tag`", nullable = true, length = 50)
    public String getTag() {
        return this.tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Rule)) return false;
        final Rule rule = (Rule) o;
        return Objects.equals(getId(), rule.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}

