/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Sysdiagrams generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`sysdiagrams`", schema = "dbo", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"`principal_id`", "`name`"})})
public class Sysdiagrams implements Serializable {

    private int diagramId;
    private String name;
    private int principalId;
    private Integer version;
    @JsonIgnore
    private byte[] definition;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`diagram_id`", nullable = false, scale = 0, precision = 10)
    public int getDiagramId() {
        return this.diagramId;
    }

    public void setDiagramId(int diagramId) {
        this.diagramId = diagramId;
    }

    @Column(name = "`name`", nullable = false, length = 255)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "`principal_id`", nullable = false, scale = 0, precision = 10)
    public int getPrincipalId() {
        return this.principalId;
    }

    public void setPrincipalId(int principalId) {
        this.principalId = principalId;
    }

    @Column(name = "`version`", nullable = true, scale = 0, precision = 10)
    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @Column(name = "`definition`", nullable = true)
    public byte[] getDefinition() {
        return this.definition;
    }

    public void setDefinition(byte[] definition) {
        this.definition = definition;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Sysdiagrams)) return false;
        final Sysdiagrams sysdiagrams = (Sysdiagrams) o;
        return Objects.equals(getDiagramId(), sysdiagrams.getDiagramId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDiagramId());
    }
}

