/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Township generated by hbm2java
 */
@Entity
@Table(name="`township`"
    ,schema="data"
)

public class Township  implements java.io.Serializable {

    
    private Integer id;
    
    private String townshipName;
    
    private Integer volumeLow;
    
    private Integer volumeHigh;
    
    private Integer auctionDay;
    
    private Set<Property> properties = new HashSet<Property>(0);
    
    private County county;
    
    private Set<Grade> grades = new HashSet<Grade>(0);

    public Township() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`ID`", precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    

    @Column(name="`township_name`", length=50)
    public String getTownshipName() {
        return this.townshipName;
    }
    
    public void setTownshipName(String townshipName) {
        this.townshipName = townshipName;
    }

    

    @Column(name="`volume_low`", precision=10)
    public Integer getVolumeLow() {
        return this.volumeLow;
    }
    
    public void setVolumeLow(Integer volumeLow) {
        this.volumeLow = volumeLow;
    }

    

    @Column(name="`volume_high`", precision=10)
    public Integer getVolumeHigh() {
        return this.volumeHigh;
    }
    
    public void setVolumeHigh(Integer volumeHigh) {
        this.volumeHigh = volumeHigh;
    }

    

    @Column(name="`auction_day`", precision=10)
    public Integer getAuctionDay() {
        return this.auctionDay;
    }
    
    public void setAuctionDay(Integer auctionDay) {
        this.auctionDay = auctionDay;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="township")
    public Set<Property> getProperties() {
        return this.properties;
    }
    
    public void setProperties(Set<Property> properties) {
        this.properties = properties;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`county_id`")
    public County getCounty() {
        return this.county;
    }
    
    public void setCounty(County county) {
        this.county = county;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="township")
    public Set<Grade> getGrades() {
        return this.grades;
    }
    
    public void setGrades(Set<Grade> grades) {
        this.grades = grades;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Township) )
		    return false;

		 Township that = (Township) o;

		 return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );

         return result;
    }


}

