/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.portal.platform.Buyer;

/**
 * Service object for domain model class Buyer.
 *
 * @see {@link Buyer}
 */
public interface BuyerService {


	/**
	 * Finds Buyer by id.
	 *
	 * @param buyerId The id of the wanted Buyer.
	 * @return The found Buyer. If no Buyer is found, this method returns null.
	 */
	Buyer getById(Integer buyerId) throws EntityNotFoundException;

	/**
	 * Finds all Buyers.
	 *
	 * @return A list of Buyers.
	 */
    @Deprecated
	Page<Buyer> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all Buyers.
	 * @return A list of Buyers.
	 */
    Page<Buyer> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Buyers in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the Buyer.
	 */
	long count(String query);

    Page<Buyer> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

