/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.portal.platform.DisbursementType;

/**
 * Service object for domain model class DisbursementType.
 *
 * @see {@link DisbursementType}
 */
public interface DisbursementTypeService {


	/**
	 * Finds DisbursementType by id.
	 *
	 * @param disbursementTypeId The id of the wanted DisbursementType.
	 * @return The found DisbursementType. If no DisbursementType is found, this method returns null.
	 */
	DisbursementType getById(Integer disbursementTypeId) throws EntityNotFoundException;

	/**
	 * Finds all DisbursementTypes.
	 *
	 * @return A list of DisbursementTypes.
	 */
    @Deprecated
	Page<DisbursementType> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all DisbursementTypes.
	 * @return A list of DisbursementTypes.
	 */
    Page<DisbursementType> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the DisbursementTypes in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the DisbursementType.
	 */
	long count(String query);

    Page<DisbursementType> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

