/*Copyright (c) 2016-2017 newlinefinancial.com All Rights Reserved.
 This software is the confidential and proprietary information of newlinefinancial.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with newlinefinancial.com*/

package com.portal.platform.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.portal.platform.PortalMatterFilter;
import com.portal.platform.PortalMatterFilterId;

/**
 * Service object for domain model class PortalMatterFilter.
 *
 * @see {@link PortalMatterFilter}
 */
public interface PortalMatterFilterService {


	/**
	 * Finds PortalMatterFilter by id.
	 *
	 * @param portalMatterFilterId The id of the wanted PortalMatterFilter.
	 * @return The found PortalMatterFilter. If no PortalMatterFilter is found, this method returns null.
	 */
	PortalMatterFilter getById(PortalMatterFilterId portalMatterFilterId) throws EntityNotFoundException;

	/**
	 * Finds all PortalMatterFilters.
	 *
	 * @return A list of PortalMatterFilters.
	 */
    @Deprecated
	Page<PortalMatterFilter> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Finds all PortalMatterFilters.
	 * @return A list of PortalMatterFilters.
	 */
    Page<PortalMatterFilter> findAll(String query, Pageable pageable);

    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the PortalMatterFilters in the repository with matching query.
     *
     * @param query query to filter results.
	 * @return The count of the PortalMatterFilter.
	 */
	long count(String query);

    Page<PortalMatterFilter> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);

}

